version: '3.8'

services:
  # Neo4j database for semantic memory/relationships
  neo4j:
    image: neo4j:5.13.0
    container_name: mem0-neo4j
    ports:
      - "7474:7474" # Neo4j Browser interface
      - "7687:7687" # Bolt protocol
    volumes:
      - ./data/neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    networks:
      - mem0-network

  # ChromaDB for vector database
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: mem0-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/vector-db:/chroma/chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - mem0-network

  # Mem0 REST API server
  mem0-server:
    image: mem0ai/mem0:latest
    container_name: mem0-api
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - chromadb
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - VECTOR_DB_URI=http://chromadb:8000
    networks:
      - mem0-network

  # React front-end for Mem0
  mem0-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mem0-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mem0-server
    networks:
      - mem0-network

networks:
  mem0-network:
    driver: bridge 